---
title: "Reproducible and programmatic analysis of flow cytometry experiments with the cytoverse"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reproducible and programmatic analysis of flow cytometry experiments with the cytoverse}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# The Cytoverse!

The `cytoverse` is a collection of open source R based tools developed by the founders of **Ozette Technologies** which facilitate programmatic analysis of flow cytometry data.

A number of packages make up the `cytoverse`. [flowCore](https://bioconductor.org/packages/release/bioc/html/flowCore.html), [flowWorkspace](https://www.bioconductor.org/packages/release/bioc/html/flowWorkspace.html), [openCyto](https://bioconductor.org/packages/release/bioc/html/openCyto.html), and [ggcyto](https://www.bioconductor.org/packages/release/bioc/html/ggcyto.html) make up the core of the `cytoverse`. These packages are, by and large, powerful and sufficient to create robust and reproducible analysis workflows for flow cytometry data. Additional available packages such as `flowClust`, `flowStats`, `CytoQC`, or `CytoML` can be further utilized for niche applications including, model based clustering of flow cytometry data, QC and standardization of set of FCS files, even parsing of workspaces from FlowJo or cytobank.

# Workshop outlines

## Learning goals

The aim of this workshop is to empower flow cytometry users and analysts towards reproducible and programmatic analysis.

By the end of this workshop, the attendees will be able to

-   Import flow cytometry data,
-   Understand the difference between **uncompensated**, **compensated**, and **transformed** data,
-   Identify and generate important plots to assess the **data** and  **quality**,
-   Identify sub-populations by manual or semi-automated gating of markers,
-   Generate plots summarizing the expression of markers and abundance of various sub-populations

## Prerequisites/assumptions

-   Some R knowledge,
-   Basic flow cytometry knowledge,
-   Willingness to ask questions and learn

## Data

For this workshop, we will use subset of a public data set: [FR-FCM-Z5PC](https://flowrepository.org/public_experiment_representations/5932) that can be found in **flowrepository.org**. The dataset was published in the following [paper](https://doi.org/10.1038/s41467-022-34638-2).

## Workshop schedule

| Activity                                         | Time       |
|--------------------------------------------------|------------|
| Basics of working with FCS files                 | 15 minutes |
| Spillover, Transformation, and Visualization (1) | 15 minutes |
| Gating Cells in the `cytoverse`                    | 40 minutes |
| Visualization (2)                                | 10 minutes |
| Reporting                                        | 10 minutes |
                                       | 10 minutes |
# Journey into the `cytoverse`!

Let's begin!    
