---
title: "Reporting: Bringing Everything Together"
output: rmarkdown::html_vignette
---

# Background

The final step in the analysis of flow cytometry data is **Reporting**. Below, we show how analysts can quickly extract counts, frequencies, and expression values for their population(s) of interest.

```{r libraries, echo=T, eval=T, message=FALSE}
library(flowCore)
library(flowWorkspace)
library(ggcyto)
library(CytoverseBioc2023)
cache_workshop_data()
```

```{r get_gatingset, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
gs = make_transformed_gs()
```

## Counts, Frequencies, and MFI

Event counts can be easily extracted in a table f

```{r counts, message = FALSE}
# get count for all
counts <- gs_pop_get_count_fast(gs,  # indicate which GatingSet to use
                                statistic = "count", # indicate what statistic is requested
                                format = "wide") # indicate if data should be in wide (samples are columns) or long (each node for each sample gets a row) format

knitr::kable(counts, caption = "Event counts")
```

```{r frequency, message = FALSE}
freq <- gs_pop_get_count_fast(gs,
                              statistic = "freq",
                              format = "wide")
knitr::kable(freq, caption = "Event frequencies relative to parent node")
```

What if one wants to report frequencies relative to a different population:

```{r}
plot(gs, bool = TRUE)
```

